export const data = [
  {
    question: "What is the capital of France?",
    option1: "Paris",
    option2: "Berlin",
    option3: " London",
    option4: "Rome",
    ans: 1,
  },
  {
    question: "Who painted the Mona Lisa?",
    option1: " Leonardo da Vinci",
    option2: " Vincent van Gogh",
    option3: "Michelangelo",
    option4: " Pablo Picasso",
    ans: 1,
  },
  {
    question: "What is the chemical symbol for water?",
    option1: "HO",
    option2: "NaCl",
    option3: "H2O",
    option4: "CO2",
    ans: 3,
  },
  {
    question: "What is the world's tallest mountain?",
    option1: "K2",
    option2: "Mount Everest ",
    option3: "Denali",
    option4: " Mount Kilimanjaro",
    ans: 2,
  },
  {
    question: "What year did World War II begin?",
    option1: "1939",
    option2: "1914",
    option3: "1945",
    option4: "1989",
    ans: 1,
  },
  {
    question: "What is the smallest country in the world by land area?",
    option1: "Vatican City",
    option2: "Monaco",
    option3: "Nauru",
    option4: "Tuvalu",
    ans: 1,
  },
  {
    question: "What is the first element on the periodic table?",
    option1: "Hydrogen",
    option2: "Helium",
    option3: "Carbon",
    option4: "Sodium",
    ans: 1,
  },
  {
    question: "What has an eye but cannot see?",
    option1: "A button",
    option2: "A potato",
    option3: "A key",
    option4: "A needle",
    ans: 4,
  },
  {
    question: "What is the largest ocean on Earth?",
    option1: "Pacific Ocean",
    option2: "Indian Ocean",
    option3: "Arctic Ocean",
    option4: "Atlantic Ocean",
    ans: 1,
  },
  {
    question: "Which planet is known as the 'Red Planet'?",
    option1: "Jupiter",
    option2: "Mars",
    option3: "Pluto",
    option4: "Venus",
    ans: 3,
  },
  {
    question: "What is the chemical symbol for gold?",
    option1: "Au",
    option2: "Go",
    option3: "AG",
    option4: "Gd",
    ans: 1,
  },
  {
    question: "Which of the following is not a primary color?",
    option1: "Purple",
    option2: "Green",
    option3: "Yellow",
    option4: "Red",
    ans: 1,
  },
  {
    question: "Who is credited with inventing the telephone?",
    option1: " Alexander Graham Bell",
    option2: "Issac Newton",
    option3: "Nikola Tesla",
    option4: "Thomas Edison",
    ans: 1,
  },
  {
    question: "What is the largest organ in the human body?",
    option1: "Skin",
    option2: "Kidney",
    option3: "Liver",
    option4: "Heart",
    ans: 1,
  },
  {
    question: "What is the chemical formula for table salt?",
    option1: "CH4",
    option2: "Nacl",
    option3: "CO2",
    option4: "HO",
    ans: 2,
  },
  {
    question: "Who is known as the 'Father of Physics'?",
    option1: "Issac Newton",
    option2: "Albert Einstein",
    option3: "Galileo Galilei",
    option4: "Nikola Tesla",
    ans: 1,
  },
  {
    question: "What is the capital of Japan?",
    option1: "Tokyo",
    option2: "Seoul",
    option3: "Beijing",
    option4: "Korea",
    ans: 1,
  },
  {
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    option1: "Amelia Earhart",
    option2: "Sally Ride",
    option3: "Valentina Tereshkova",
    option4: "Bessie Coleman",
    ans: 1,
  },
  {
    question: "What is the smallest planet in our solar system?",
    option1: "Mercury",
    option2: "Pluto",
    option3: "Mars",
    option4: "Earth",
    ans: 1,
  },
  {
    question:
      "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
    option1: "A globe",
    option2: " A Map",
    option3: " A dream",
    option4: "A Painting",
    ans: 2,
  },
];
